### ISSUE TITLE
Invalid Account Number format

### ISSUE THREAD

**Issue by shah-smit** [mavi888/cdk-pipelines-example#1]
When running the below:
```
npx cdk bootstrap \
  --profile default \
  --cloudformation-execution-policies arn:aws:iam::aws:policy/AdministratorAccess \
  aws://123455678/ap-southeast-1
```

Getting the below error:

```
/Users/Smit/Downloads/cdk-pipelines-example/node_modules/@aws-cdk/cx-api/lib/environment.ts:29
        'Expected format: aws://account/region');
            ^
Error: Unable to parse environment specification "aws://ACCOUNTNUMBER/REGION". Expected format: aws://account/region
    at Function.parse (/Users/Smit/Downloads/cdk-pipelines-example/node_modules/@aws-cdk/cx-api/lib/environment.ts:29:13)
    at new CloudFormationStackArtifact (/Users/Smit/Downloads/cdk-pipelines-example/node_modules/@aws-cdk/cx-api/lib/artifacts/cloudformation-artifact.ts:109:41)
    at Function.fromManifest (/Users/Smit/Downloads/cdk-pipelines-example/node_modules/@aws-cdk/cx-api/lib/cloud-artifact.ts:47:16)
    at CloudAssembly.renderArtifacts (/Users/Smit/Downloads/cdk-pipelines-example/node_modules/@aws-cdk/cx-api/lib/cloud-assembly.ts:202:43)
    at new CloudAssembly (/Users/Smit/Downloads/cdk-pipelines-example/node_modules/@aws-cdk/cx-api/lib/cloud-assembly.ts:54:27)
    at CloudAssemblyBuilder.buildAssembly (/Users/Smit/Downloads/cdk-pipelines-example/node_modules/@aws-cdk/cx-api/lib/cloud-assembly.ts:313:12)
    at Object.synthesize (/Users/Smit/Downloads/cdk-pipelines-example/node_modules/@aws-cdk/core/lib/private/synthesis.ts:41:18)
    at App.synth (/Users/Smit/Downloads/cdk-pipelines-example/node_modules/@aws-cdk/core/lib/stage.ts:188:23)
    at Object.<anonymous> (/Users/Smit/Downloads/cdk-pipelines-example/bin/cdk-pipelines-demo.ts:11:5)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
Subprocess exited with error 1
```

PS: `123455678` is random.

**Comment by shah-smit** [comment]
Manage to resolve it... Had to update all the files that required account number and region scope.
